class ConcreteProductA1: AbstractProduct()
class ConcreteProductA2: AbstractProduct()
class ConcreteProductA3: AbstractProduct()
class ConcreteProductB1: AbstractProduct()
class ConcreteProductB2: AbstractProduct()
class ConcreteProductB3: AbstractProduct()
class NullProduct: AbstractProduct()